### ISSUE TITLE
Bug report for Arm A64 asim.80

### ISSUE THREAD

**Issue by TabeenRaoof** [computation-structures/asim#2]
When trying to assemble the instructions below, the #16 is assembled as 10
  mov X2, #16
  mov X1, 5
  add X3, X1, X2

The result is X3 will be assigned a value of 15 instead of 21. 

See the attached screenshot for details.

![Screen Shot 2024-03-13 at 1 59 03 AM (2)](https://github.com/computation-structures/asim/assets/71104701/fc2ff240-cf09-4e72-9a24-bc6c9ee24431)

**Comment by terman** [comment]
Note that all the numbers in the state display of the simulator are shown in hexadecimal (base 16), written with a "0x" prefix.  16 decimal is the same as 0x10 in hexadecimal.
